### ISSUE TITLE
DB query errors

### ISSUE THREAD

**Issue by merlinfive** [CarlosCuezva/dashboards-Grafana-Teslamate#17]
Hi , I like your dashboards but why do I get nearly everywere db query errors ?

e.a. db query error: pq: syntax error at or near "*"

![image](https://user-images.githubusercontent.com/101570702/230039481-390e5fe8-30cc-4f78-9468-ed7176cf12a3.png)
some of your dashboards are fine too 

e.a
![image](https://user-images.githubusercontent.com/101570702/230041879-ba374b78-d70a-46fb-9b65-ae40259498bd.png)

seems only "battery health" has issues

battery health dashboard from other github is working fine 

![image](https://user-images.githubusercontent.com/101570702/230043424-e5f93733-d87f-46a9-a7f7-86b3f69d86fb.png)

**Comment by CarlosCuezva** [comment]
Hi merlinfive.

I have been reviewing your problem and if I am not mistaken, it is because you do not have registered recharges where you have added more than 10kWh in one session.

You can go to the "charges" dashboard and look at the "Added" column

![Captura de pantalla 2023-04-05 a las 13 21 03](https://user-images.githubusercontent.com/5815421/230066114-e7c50e1f-c387-4cfb-bfb1-607e6fe2588d.png)

**Comment by merlinfive** [comment]
ok I have setup teslamate the last days to use teslasolarcharger and used only little , so if I understand right I need at lease a charge with 10kWh in a single session to get correct numbers , thats fine than will check again after a "bigger" charge next week , thanks !

![image](https://user-images.githubusercontent.com/101570702/230073786-25d632ba-3bcf-4d1f-b3fe-b36e776157c4.png)

**Comment by CarlosCuezva** [comment]
Thanks to you and enjoy the dashboards, if with more data it continues to fail you please let me know.

Regards

**Comment by merlinfive** [comment]
Hi , 

yes information were fine , right now I'm without a Tesla , new  S Plaid wil be delivered next week :-)

**Comment by CarlosCuezva** [comment]
Ohhh, good luck with the wait 😍

So I close the issue
